Ascii converter
lrustand/vhdl_prosjekt pull request #16
Opened 2021-11-24 07:35 UTC by os021

2021-11-24 08:30 UTC, lrustand requested changes

2021-11-24 08:30 UTC, lrustand commented on ascii_to_five_bit.vhd
> +            converted_ascii: out std_logic_vector(7 downto 0));
Vi kan endre converted_ascii til 5 bit, siden det blir plass til enter

2021-11-24 08:30 UTC, lrustand commented on ascii_to_five_bit.vhd
> +        if ( ascii_in(7 downto 5) >= "010" and ascii_in(4 downto 0) > "0001" and ascii_in(4 downto 0) < "11011" ) then
Man trenger ikke parentes rundt if expressions

2021-11-24 08:30 UTC, lrustand commented on five_bit_to_ascii_tb.vhd
> +    end process;
Hvis du legger på en wait statement uten argumenter på slutten av prosessen så slipper vi at den fortsetter å kjøre uendelig. Samme på den andre testbenken

2021-11-24 08:30 UTC, lrustand commented on ascii_to_five_bit.vhd
> +use ieee.numeric_std.all;
Konsekvent bruk av upper/lowercase ser bedre ut. I andre filer tror jeg vi har IEEE med store bokstaver og annet med små: use IEEE.std_logic_1164.all

2021-11-24 08:30 UTC, lrustand commented on ascii_to_five_bit.vhd
> +        elsif ( ascii_in = "00001101" ) then
Her er det muligens enklere å skrive det i hex: x"0d"

2021-11-24 08:30 UTC, lrustand commented on five_bit_to_ascii_tb.vhd
> +    test_in <= "01100";
Her mangler det indentering

2021-11-24 08:30 UTC, lrustand commented on five_bit_to_ascii_tb.vhd
> +    clk<='0';
Her mangler det indentering

2021-11-24 08:30 UTC, lrustand commented on five_bit_to_ascii.vhd
> +ascii_out<= "011" & std_logic_vector(unsigned(five_bit_in) + "1");
Her mangler det indentering

2021-11-24 08:30 UTC, lrustand commented on ascii_to_five_bit_tb.vhd
> +    test_in <= "01001100";
Her mangler det indentering

2021-11-24 08:30 UTC, lrustand commented on ascii_to_five_bit_tb.vhd
> +    clk<='0';
Her mangler det indentering

2021-11-24 09:04 UTC, os021 commented on ascii_to_five_bit.vhd
> +            converted_ascii: out std_logic_vector(7 downto 0));
OK

2021-11-24 09:05 UTC, os021 commented on ascii_to_five_bit.vhd
> +        if ( ascii_in(7 downto 5) >= "010" and ascii_in(4 downto 0) > "0001" and ascii_in(4 downto 0) < "11011" ) then
OK

2021-11-24 09:08 UTC, os021 commented on five_bit_to_ascii_tb.vhd
> +    end process;
ok

2021-11-24 09:10 UTC, os021 commented on ascii_to_five_bit.vhd
> +use ieee.numeric_std.all;
ok

2021-11-24 09:17 UTC, os021 commented on five_bit_to_ascii_tb.vhd
> +    test_in <= "01100";
ok

2021-11-24 09:17 UTC, os021 commented on five_bit_to_ascii_tb.vhd
> +    clk<='0';
ok

2021-11-24 09:17 UTC, os021 commented on ascii_to_five_bit_tb.vhd
> +    test_in <= "01001100";
ok

2021-11-24 09:18 UTC, os021 commented on five_bit_to_ascii.vhd
> +ascii_out<= "011" & std_logic_vector(unsigned(five_bit_in) + "1");
ok

2021-11-24 09:19 UTC, os021 commented on ascii_to_five_bit_tb.vhd
> +    clk<='0';
ok

2021-11-24 09:19 UTC, os021 commented on ascii_to_five_bit.vhd
> +        elsif ( ascii_in = "00001101" ) then
Jeg synes det er lettere å jobbe med binær

2021-11-24 11:28 UTC, Nelde95 requested changes
Fjærn work-obj93.cf

2021-11-24 11:40 UTC, lrustand requested changes

2021-11-24 11:40 UTC, lrustand commented on ascii_to_five_bit.vhd
> +
Vi kan ta vekk sånne

2021-11-24 11:40 UTC, lrustand commented on ascii_to_five_bit_tb.vhd
> +        begin
begin skal ikke være indentert

2021-11-24 11:40 UTC, lrustand commented on ascii_to_five_bit_tb.vhd
> +        begin
Samme her

2021-11-24 11:40 UTC, lrustand commented on ascii_to_five_bit_tb.vhd
> +        test_in <= "01110111";
Jeg vil veldig gjerne ha ascii i hex

2021-11-24 11:40 UTC, lrustand commented on work-obj93.cf
> +  architecture behavioral of ascii_to_five_bit at 42( 1050) + 0 on 20;
Fjerne denne

2021-11-24 11:40 UTC, lrustand commented on five_bit_to_ascii_tb.vhd
> +signal test_in: std_logic_vector(4 downto 0);
Indentere component og signal

2021-11-24 11:40 UTC, lrustand commented on .gitignore
> +work-obj93.cf
Kan gjerne bytte til *.cf og *.vcd. Og evt andre patterns som matcher filer fra ghdl
Edit: og *.o

2021-11-24 11:42 UTC, lrustand commented on ascii_to_five_bit.vhd
> +        if ascii_in(6 downto 5) >= "10" and ascii_in(4 downto 0) > "00001" and ascii_in(4 downto 0) < "11011" then
Kan vi bytte til å sjekke mot ascii hex, så blir denne mye mer lesbar

2021-11-24 11:46 UTC, os021 commented on ascii_to_five_bit.vhd
> +
ok

2021-11-24 11:46 UTC, os021 commented on ascii_to_five_bit_tb.vhd
> +        begin
ok

2021-11-24 11:46 UTC, os021 commented on ascii_to_five_bit_tb.vhd
> +        begin
ok

2021-11-24 11:47 UTC, os021 commented on work-obj93.cf
> +  architecture behavioral of ascii_to_five_bit at 42( 1050) + 0 on 20;
ok

2021-11-24 11:50 UTC, os021 commented on .gitignore
> +work-obj93.cf
ok

2021-11-24 11:50 UTC, os021 commented on five_bit_to_ascii_tb.vhd
> +signal test_in: std_logic_vector(4 downto 0);
ok

2021-11-24 12:08 UTC, os021 commented on ascii_to_five_bit.vhd
> +        if ascii_in(6 downto 5) >= "10" and ascii_in(4 downto 0) > "00001" and ascii_in(4 downto 0) < "11011" then
ok

2021-11-24 12:08 UTC, os021 commented on ascii_to_five_bit_tb.vhd
> +        test_in <= "01110111";
ok

2021-11-24 13:28 UTC, lrustand commented on work-obj93.cf
> +  architecture behavioral of ascii_to_five_bit at 42( 1050) + 0 on 20;
Den er der fortsatt

2021-11-24 13:31 UTC, lrustand commented on ascii_to_five_bit.vhd
> +        if ascii_in(6 downto 5) >= "10" and ascii_in(4 downto 0) > "00001" and ascii_in(4 downto 0) < "11011" then
Her endret du den nederste if-en, men ikke den øverste

2021-11-24 13:33 UTC, lrustand requested changes
Det hjalp, men noen av kommentarene er fortsatt gyldig. Har resolva de tingene som er fikset og kommet med ny kommentar på de som fortsatt mangler

2021-11-26 06:58 UTC, lrustand requested changes

2021-11-26 06:58 UTC, lrustand commented on ascii_to_five_bit.vhd
> +        if ascii_in(6 downto 5) >= x"2" and ascii_in(4 downto 0) >= x"1" and ascii_in(4 downto 0) < x"1b" then
Hmm, ikke helt sånn jeg hadde sett for meg. Kan du sammenligne hele ascii_in mot hele ascii-verdier?

```vhdl
if (ascii_in >= x"41" and ascii_in <= x"5a") or
   (ascii_in >= x"61" and ascii_in <= x"7a") then
```
Vet ikke om den her gjør det samme som din, men denne sjekker om det er enten a-z eller A-Z, denne er sakset fra controlpath

2021-11-26 07:55 UTC, Nelde95 commented on ascii_to_five_bit.vhd
> +        if ascii_in(7 downto 0) > x"40" and ascii_in(7 downto 0) < x"5b" or ascii_in(7 downto 0) > x"60" and ascii_in(7 downto 0) < x"7b"then
(7 downto 0) unødvendig når det er hele vektoren

2021-11-26 08:33 UTC, os021 commented on ascii_to_five_bit.vhd
> +        if ascii_in(7 downto 0) > x"40" and ascii_in(7 downto 0) < x"5b" or ascii_in(7 downto 0) > x"60" and ascii_in(7 downto 0) < x"7b"then
OK

2021-11-26 08:36 UTC, Nelde95 approved these changes
Ser bra ut

2021-11-26 09:22 UTC, lrustand approved these changes

2021-11-26 09:23 UTC, merged