implemented counter
lrustand/vhdl_prosjekt pull request #21
Opened 2021-11-24 09:25 UTC by os021

2021-11-24 09:59 UTC, Nelde95 commented on enimga_counter.vhd
Default kommentar er litt overflødig

2021-11-24 09:59 UTC, Nelde95 commented on enimga_counter.vhd
>  -- Uncomment the following library declaration if using
Samme som over

2021-11-24 12:21 UTC, lrustand submitted a review, later dismissed
Ser bra ut for meg, hvis Edvards kommentarer fikses

2021-11-25 21:06 UTC, lrustand requested changes
Se litt nøyere på den siste commiten her, den gjør ikke det du skriver at den gjør. Det står at den fjerner default tekst, men egentlig legger den bare til en fil som ikke skal være der

2021-11-25 21:10 UTC, os021 commented
Jeg sliter litt med gitt, koden på pc er korrekt men den i github blir ikke oppdatert

2021-11-26 06:50 UTC, lrustand requested changes
Da så det riktig ut. Får du squasha de to siste commitene også, så vi slipper å ha to med samme melding? Og det er forresten skrivefeil i filnavnet

2021-11-26 10:12 UTC, Nelde95 approved these changes, later dismissed
Looks good

2021-11-26 10:20 UTC, lrustand approved these changes

2021-11-26 10:20 UTC, Nelde95 approved these changes

2021-11-26 10:21 UTC, merged