Top_level
lrustand/vhdl_prosjekt pull request #24
Opened 2021-11-26 11:30 UTC by thomaskaafjeld

2021-11-26 11:45 UTC, lrustand requested changes

2021-11-26 11:45 UTC, lrustand commented on reg5bit.vhd
> +end reg5;
Kan vi ta vekk clr, rst og clk?

2021-11-26 11:45 UTC, lrustand commented on top_level.vhd
> +    --signal tx                : std_logic;
Ta vekk utkommentert signal

2021-11-26 11:45 UTC, lrustand commented on top_level.vhd
> +    signal data13, data23                                 : std_logic_vector(4 downto 0);
Vi kan vurdere om det er bedre å bruke romertall for rotor-nummerering her (rom_så ser vi hvilket tall som har med rotor å gjøre. Evt endre til noe som rom1_addr1 eller rom_addr1a eller noe.

2021-11-27 16:34 UTC, Nelde95 reviewed
Logikken virker riktig nå. Er ikke alltid så lett å velge variabel navn når det blir så mange ting som skal kobles, men kan jeg eventuelt fåreslå å bruke noen navn som plugboard_to_i, i_to_j, j_to_i og k_to_reflector? så er det litt tydeligere hvor det går fra og til?

2021-11-28 02:18 UTC, Nelde95 approved these changes, later dismissed
Ser bra ut for min del nå

2021-11-29 09:14 UTC, lrustand approved these changes

2021-11-29 10:02 UTC, Nelde95 approved these changes

2021-11-29 10:04 UTC, os021 approved these changes

2021-11-29 10:04 UTC, merged